spring.application.name=producto-provedores
# =====================================================
# CONFIGURACIÓN DEL SERVIDOR
# =====================================================
server.port=8082
server.servlet.context-path=/api/productos

# =====================================================
# CONFIGURACIÓN DE LA BASE DE DATOS
# =====================================================
spring.datasource.url=jdbc:mysql://localhost:3306/tienda_generica_producto_provedor?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1074129082
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =====================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# =====================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true